In [1]:
import torch

In [8]:
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4.shape


torch.Size([2, 2, 3])

In [19]:
#In case of 3D: first index is to choose which slice/matrix/depth. The other two are row/column for this slice.
#note: you can't get a column by indexing twice
print(t4[1][0])
print(t4[1][:][0]) #same as the previous line. It means choose all rows in the matrix then choose the row 1

tensor([15., 16., 17.])
tensor([15., 16., 17.])


In [20]:
# Matrix: Note that it's not possible to create tensors with an improper shape.

t5 = torch.tensor([[5., 6, 11], 
                   [7, 8], 
                   [9, 10]])
t5


ValueError: expected sequence of length 3 at dim 1 (got 2)

# autograd (automatic gradients).
1. If you have an output y that is function of tensors with .tensor(val,requires_grad=True). The gradients of these tensors will automatically update when you do y.backward()
2. if you have multiple outputs (e.g. y2 and y22) and they are functions of the same tensors, tensor.grad would hold the sum of all gradients.
3. to find the gradient w.r.t a specific output, you need to use torch.autograd.grad(func,tens)
4. To reduce memory usage, during the .backward() call, all the intermediary results are deleted when they are not needed anymore. Hence if you try to call .backward() twice, you have to .backward(retain_graph=True ) .


In [56]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

# Arithmetic operations
y = w * x + b

y.backward()

# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)



dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [58]:
#here we don't call .backward hence no grads
# Create tensors.
x1 = torch.tensor(3.)
w1 = torch.tensor(4., requires_grad=True)
b1 = torch.tensor(5., requires_grad=True)

# Arithmetic operations
y1 = w1 * x1 + b1

# Display gradients
print('dy/dx:', x1.grad)
print('dy/dw:', w1.grad)
print('dy/db:', b1.grad)



dy/dx: None
dy/dw: None
dy/db: None


In [62]:
#here we do multiple calls of .backward
# Create tensors.
x2 = torch.tensor(3.,requires_grad=True)
w2 = torch.tensor(4., requires_grad=True)
b2 = torch.tensor(5., requires_grad=True)

# Arithmetic operations
y2 = w2 * x2 + b2
y22 = w2*x2*x2 + b2 #random operation just to test the effect on x.grad

y2.backward(retain_graph=True )
y22.backward(retain_graph=True )
# Display gradients
print('dy/dx:', x2.grad)
print('dy/dw:', w2.grad)
print('dy/db:', b2.grad)

print("\ndy/dx decomposed:\n")
print('dy2/dx:', torch.autograd.grad(y2,x2))
print('dy22/dx:', torch.autograd.grad(y22,x2))


dy/dx: tensor(28.)
dy/dw: tensor(12.)
dy/db: tensor(2.)

dy/dx decomposed:

dy2/dx: (tensor(4.),)
dy22/dx: (tensor(24.),)


In [76]:
t1 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])

print(t3.shape)

t2 = torch.full((3, 2), 42) #creates a tensor with fixed val
t3 = torch.cat((t1, t2)) #concat


print(t1.shape, t2.shape, t3.shape)
print(t3)


torch.Size([6, 2])
torch.Size([3, 2]) torch.Size([3, 2]) torch.Size([6, 2])
tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])


In [92]:
t1 = torch.full((3, 2), 42)
t2 = torch.full((3, 2,1), 42)
print(t1,'\n\n',t2)
print("\n\n although comparison gives true, one dim is not the same as 1 dim\n\n")
print(t1[0])
print(t2[0])
print(t1[0] == t2[0])

t3 = torch.cat((t1[0], t2[0])) #error
t3 = torch.cat((t1, t2)) #error



tensor([[42, 42],
        [42, 42],
        [42, 42]]) 

 tensor([[[42],
         [42]],

        [[42],
         [42]],

        [[42],
         [42]]])


 although comparison gives true, one dim is not the same as 1 dim


tensor([42, 42])
tensor([[42],
        [42]])
tensor([[True, True],
        [True, True]])


RuntimeError: Tensors must have same number of dimensions: got 1 and 2